services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=monitoring
  api:
    image: myapp
    depends_on:
      - db
    ports:
      - 9000:8080
    build:
      dockerfile: ./Dockerfile
      context: .