services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - POSTGRES_DB=monitoring
  api:
    image: myapp
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      - DB_HOST=db
      - DB_PASSWORD=root
      - DB_USER=postgres
      - DB_NAME=monitoring
    build:
      dockerfile: ./Dockerfile
      context: .